export const state = {
  currencyCounter: 0,
  currencyPerClick: 1,
  extraCurrency: 0, // extra currency for Customisation

  isHovering: false, // is the mouse hovering over the bug
  optionsOpen: false,
  shopOpen: false,
  achievementsOpen: false,
  customisationOpen: false,
  statisticsOpen: false,
  exportcsvPopupOpen: false,
  resetPopupOpen: false,

  /* boughtUpgrades object initialization
  these are always 0 ! */
  boughtUpgrades: {
    ask_on_reddit: 0,
    google_it: 0,
    tell_chatgtp_to_do_it: 0,
    read_the_documentation: 0,
    rubber_duck_debugger: 0,
    git_gud: 0,
    null_pointer_wand: 0,
    debugging_goggles: 0,
    spaghetti_code_chef: 0,
    fof_finder: 0,
    overclocked_brain: 0,
    boolean_blender: 0,
    ai_pair_programmer: 0,
    ctrlz_mastery: 0,
    dark_mode_dev: 0,
    keyboard_masher: 0,
    the_agile_anvil: 0,
    quantum_commenter: 0,
    css_sorcerer: 0,
    overengineer_supreme: 0,
    big_o_optimizer: 0,
    infinite_retry_protocol: 0,
    console_log_overload: 0,
    tech_debt_digger: 0,
  },

  boughtHats: {
    blueCappie_svg: false,
    greenCappy_svg: false,
    redCappy_svg: false,
    yellowCappy_svg: false,
    firemanshelmet_svg: false,
    greaduationhat_svg: false,
    helmet_svg: false,
    sunhat_svg: false,
    tophat_svg: false,
    tophatwhite_svg: false,
    crown_svg: false,
    empty_svg: true,
  },

  statistics: {
    total_clicks: 0,
    total_currency: 0,
    total_upgrades_bought: 0,
    total_currency_spent: 0,
    total_rubys_collected: 0,
    total_rubys_spent: 0,
    total_roaches_caught: 0,
    total_roaches_missed: 0,
    total_hats_bought: 0,
    total_achievements_earned: 0,
  },

  achievements: {
    first_bug_fixed: 0,
    "100_bugs_fixed": 0,
    "1000_bugs_fixed": 0,
    "10000_bugs_fixed": 0,
    "100000_bugs_fixed": 0,
    "1000000_bugs_fixed": 0,
    "10000000_bugs_fixed": 0,
    "100000000_bugs_fixed": 0,
    "1000000000_bugs_fixed": 0,
    "100_times_asked_on_reddit": 0,
    "100_times_googled": 0,
    "100_times_used_ChatGPT": 0,
    "100_times_read_the_documentation": 0,
    "100_times_used_rubber_duck_debugging": 0,
    "100_times_improved_your_git_skills": 0,
    "100_times_used_the_null_pointer_wand": 0,
    "100_times_used_debugging_goggles": 0,
    "100_times_improved_spaghetti_code": 0,
    "100_times_located_the_404": 0,
    "100_times_overclocked_your_brain": 0,
    "100_times_blended_the_boolean": 0,
    "100_times_used_ai_pair_programming": 0,
    "100_times_mastered_the_art_of_ctrl_z": 0,
    "100_times_used_dark_mode": 0,
    "100_times_mashed_the_keyboard": 0,
    "100_times_used_the_agile_anvil": 0,
    "100_times_used_a_quantum_commenter": 0,
    "100_times_become_a_css_sorcerer": 0,
    "100_times_overengineered": 0,
    "100_times_used_the_big_o_optimizer": 0,
    "100_times_used_the_infinte_retry_protocol": 0,
    "100_times_overloaded_the_console_log": 0,
    "100_times_found_sins_in_ancient_repos": 0,
  },
};
