export const achievements = [
  {
    id: "first_bug_fixed",
    name: "First bug fixed",
    description: "Congrats! But it was just the start...",
    achieved: false,
    condition: 1,
  },
  {
    id: "100_bugs_fixed",
    name: "100 bugs fixed",
    description: "You are getting good at this!",
    achieved: false,
    condition: 100,
  },
  {
    id: "1000_bugs_fixed",
    name: "1.000 bugs fixed",
    description: "Keep going!",
    achieved: false,
    condition: 1000,
  },
  {
    id: "10000_bugs_fixed",
    name: "10.000 bugs fixed",
    description: "Incredible clicking technique!",
    achieved: false,
    condition: 10000,
  },
  {
    id: "100000_bugs_fixed",
    name: "100.000 bugs fixed",
    description: "Ok, now it starts to get cruel.",
    achieved: false,
    condition: 100000,
  },
  {
    id: "1000000_bugs_fixed",
    name: "1.000.000 bugs fixed",
    description: "Oh my god...",
    achieved: false,
    condition: 1000000,
  },
  {
    id: "10000000_bugs_fixed",
    name: "10.000.000 bugs killed",
    description: "I have to tell authorities about you!",
    achieved: false,
    condition: 10000000,
  },
  {
    id: "100000000_bugs_fixed",
    name: "100.000.000 bugs killed",
    description: "Are you enjoying this, you cruel monster?",
    achieved: false,
    condition: 100000000,
  },
  {
    id: "1000000000_bugs_fixed",
    name: "De̵͊a͗͟t̛͕h̝͚ͪ t͢o t̐́he͐ bu͎ͣ̎g̼s͝",
    description: "Yͯ͑͜o̗u ki͈ͩl̟̠̀̐ͣ̀̈́l͇̜̄͗e̿͂d̙ t̪͔͒ͥͫ̍̕ḧ̸̡́̑ͤ̌e͉̘̅̄ͅm̶͉͕͕̂ͮ̉ a̮l͇̫͕̖̇̌͒l̞̙̀͂ͦ͘",
    achieved: false,
    condition: 1000000000,
  },
];

export const upgradeAchievements = [
  {
    id: "100_times_asked_on_reddit",
    name: "100 times asked on reddit",
    description: "Those guys really love to help.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_googled",
    name: "100 times googled",
    description: "StackOverflow provides useful bugfixes! And trolls!",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_ChatGPT",
    name: "100 times used ChatGPT",
    description: "One step closer to SkyNet!",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_read_the_documentation",
    name: "100 times read the documentation",
    description: "You should have done that in the first place!",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_rubber_duck_debugging",
    name: "100 times used rubber duck debugging",
    description: "That duck is getting tired of you.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_improved_your_git_skills",
    name: "100 times improved your git skills",
    description: "Git gud, git better!",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_the_null_pointer_wand",
    name: "100 times used the Null Pointer Wand",
    description: "It crashes everything, even your dreams.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_debugging_goggles",
    name: "100 times used debugging goggles",
    description: "You can see the bugs now, but can you fix them?",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_improved_spaghetti_code",
    name: "100 times improved spaghetti code",
    description: "You are a true code chef!",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_located_the_404",
    name: "100 times located the 404",
    description: "How did you even do that?",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_overclocked_your_brain",
    name: "100 times overclocked your brain",
    description: "I hope you have a good cooling system.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_blended_the_boolean",
    name: "100 times blended the boolean",
    description: "Sometimes a maybe is all you need.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_ai_pair_programming",
    name: "100 times used AI pair programming",
    description: "Thats how you get a job in 2023.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_mastered_the_art_of_ctrl_z",
    name: "100 times mastered the art of Ctrl-Z",
    description: "Btw, ɏꝋᵾ ȼⱥꞥ ꞥēꝟēɍ ᵾꞥđꝋ ⱦħē ꝑⱥꞩⱦ",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_dark_mode",
    name: "100 times used dark mode",
    description: "Dark mode is the only mode.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_mashed_the_keyboard",
    name: "100 times mashed the keyboard",
    description: "Sometimes you just have to let it out.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_the_agile_anvil",
    name: "100 times used the agile anvil",
    description: "Agile is not just a buzzword, its a way of life.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_a_quantum_commenter",
    name: "100 times used a quantum commenter",
    description: "This is not cheating, its just advanced debugging.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_become_a_css_sorcerer",
    name: "100 times become a css sorcerer",
    description: "CSS is magic, and you are the wizard.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_overengineered",
    name: "100 times overengineered",
    description: "Why are you like this?",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_the_big_o_optimizer",
    name: "100 times used the Big O Optimizer",
    description: "Big O can be intriguing.",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_used_the_infinte_retry_protocol",
    name: "100 times used the infinte retry protocol",
    description: "I mean, it works, right?",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_overloaded_the_console_log",
    name: "100 times overloaded the console log",
    description: "You have a lot to say, dont you?",
    achieved: false,
    condition: 100,
  },
  {
    id: "100_times_found_sins_in_ancient_repos",
    name: "100 times found sins in ancient repos",
    description: "Thank you for your service.",
    achieved: false,
    condition: 100,
  },
];
