const upgrade_definitions = [
  {
    id: "ask_on_reddit",
    name: "Ask on Reddit",
    base_cost: 10,
    price_multiplier: 1.15,
    fpc: 1,
    description: "It works on my machine...",
  },
  {
    id: "google_it",
    name: "Google it",
    base_cost: 200,
    price_multiplier: 1.2,
    fpc: 10,
    description: "Copy code from StackOverflow",
  },
  {
    id: "tell_chatgtp_to_do_it",
    name: "Tell ChatGPT to do it",
    base_cost: 500,
    price_multiplier: 1.3,
    fpc: 200,
    description: "Im a Vibe-Coder.",
  },
  {
    id: "read_the_documentation",
    name: "Read the Documentation",
    base_cost: 1000,
    price_multiplier: 1.5,
    fpc: 500,
    description: "RTFM!",
  },
  {
    id: "rubber_duck_debugger",
    name: "Rubber Duck Debugger",
    base_cost: 50000,
    price_multiplier: 1.5,
    fpc: 1000,
    description: "Talks more sense than your team.",
  },
  {
    id: "git_gud",
    name: "Git Gud",
    base_cost: 100000,
    price_multiplier: 1.5,
    fpc: 2000,
    description: "Now with fewer merge conflicts!",
  },
  {
    id: "null_pointer_wand",
    name: "Null Pointer Wand",
    base_cost: 250000,
    price_multiplier: 1.5,
    fpc: 6000,
    description: "Magically crashes everything.",
  },
  {
    id: "debugging_goggles",
    name: "Debugging Goggles",
    base_cost: 500000,
    price_multiplier: 1.5,
    fpc: 10000,
    description: "See Bugs in 4D.",
  },
  {
    id: "spaghetti_code_chef",
    name: "Spaghetti Code Chef",
    base_cost: 1000000,
    price_multiplier: 1.5,
    fpc: 20000,
    description: "My flavour of Chaos.",
  },
  {
    id: "fof_finder",
    name: "404 Finder",
    base_cost: 1100000,
    price_multiplier: 1.5,
    fpc: 25000,
    description: "Locate the unlocatable.",
  },
  {
    id: "overclocked_brain",
    name: "Overclocked Brain",
    base_cost: 1200000,
    price_multiplier: 1.5,
    fpc: 32000,
    description: "12 Threads of regret.",
  },
  {
    id: "boolean_blender",
    name: "Boolean Blender",
    base_cost: 1500000,
    price_multiplier: 1.5,
    fpc: 40000,
    description: "True, false, maybe?",
  },
  {
    id: "ai_pair_programmer",
    name: "AI Pair Programmer",
    base_cost: 1750000,
    price_multiplier: 1.5,
    fpc: 50000,
    description: "Smarter than you.",
  },
  {
    id: "ctrlz_mastery",
    name: "Ctrl+Z Mastery",
    base_cost: 1900000,
    price_multiplier: 1.5,
    fpc: 60000,
    description: "Undo your life decisions.",
  },
  {
    id: "dark_mode_dev",
    name: "Dark Mode Dev",
    base_cost: 2000000,
    price_multiplier: 1.5,
    fpc: 70000,
    description: "Types 17% faster at night.",
  },
  {
    id: "keyboard_masher",
    name: "Keyboard Masher",
    base_cost: 2200000,
    price_multiplier: 1.5,
    fpc: 80000,
    description: "It's not a bug, it's jazz.",
  },
  {
    id: "the_agile_anvil",
    name: "The Agile Anvil",
    base_cost: 2500000,
    price_multiplier: 1.5,
    fpc: 90000,
    description: "Crushes all Waterfall dreams.",
  },
  {
    id: "quantum_commenter",
    name: "Quantum Commenter",
    base_cost: 2750000,
    price_multiplier: 1.5,
    fpc: 10000,
    description: '"Top 1% commenter."',
  },
  {
    id: "css_sorcerer",
    name: "CSS Sorcerer",
    base_cost: 3000000,
    price_multiplier: 1.5,
    fpc: 120000,
    description: "Align divs with dark magic!",
  },
  {
    id: "overengineer_supreme",
    name: "Overengineer Supreme",
    base_cost: 3200000,
    price_multiplier: 1.5,
    fpc: 150000,
    description: "Deploy 100 microservices to 0 users.",
  },
  {
    id: "big_o_optimizer",
    name: "Big O Optimizer",
    base_cost: 3500000,
    price_multiplier: 1.6,
    fpc: 200000,
    description: "Now with 30% less lag!",
  },
  {
    id: "infinite_retry_protocol",
    name: "Infinite Retry Protocol",
    base_cost: 3750000,
    price_multiplier: 1.7,
    fpc: 250000,
    description: "Hope is a Strategy!",
  },
  {
    id: "console_log_overload",
    name: "Console Log Overload",
    base_cost: 4000000,
    price_multiplier: 1.8,
    fpc: 500000,
    description: "Find bugs between your printouts.",
  },
  {
    id: "tech_debt_digger",
    name: "Tech Debt Digger",
    base_cost: 10000000,
    price_multiplier: 2,
    fpc: 1000000,
    description: "Find ancient sins in the Repo.",
  },
];
